name: Build .NET Packages and Push to Octopus

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      application_type:
        description: 'Application Type to Build'
        required: true
        type: choice
        options:
          - console-app
          - web-api
          - both
        default: 'both'
      
      version_override:
        description: 'Version Override (optional)'
        required: false
        type: string
        default: ''

jobs:
  build-and-push-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: |
          if [ "${{ github.event.inputs.application_type }}" = "console-app" ] || [ "${{ github.event.inputs.application_type }}" = "both" ]; then
            dotnet restore dotnet-app/SampleDotNetApp.csproj
          fi
          if [ "${{ github.event.inputs.application_type }}" = "web-api" ] || [ "${{ github.event.inputs.application_type }}" = "both" ]; then
            dotnet restore dotnet-webapi/SampleDotNetWebApi.csproj
          fi
          
      - name: Build Console Application
        if: github.event.inputs.application_type == 'console-app' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-app
          dotnet build --configuration Release --no-restore
          
      - name: Build Web API Application
        if: github.event.inputs.application_type == 'web-api' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-webapi
          dotnet build --configuration Release --no-restore
          
      - name: Generate Version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version_override }}" ]; then
            echo "version=${{ github.event.inputs.version_override }}" >> $GITHUB_OUTPUT
          else
            echo "version=1.0.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
          echo "Generated version: ${{ steps.version.outputs.version }}"
          
      - name: Publish Console Application
        if: github.event.inputs.application_type == 'console-app' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-app
          dotnet publish --configuration Release --output ./publish --no-build
          
      - name: Publish Web API Application
        if: github.event.inputs.application_type == 'web-api' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-webapi
          dotnet publish --configuration Release --output ./publish --no-build
          
      - name: Create Console App Package
        if: github.event.inputs.application_type == 'console-app' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-app
          mkdir -p package
          cp -r publish/* package/
          echo "Version: ${{ steps.version.outputs.version }}" > package/version.txt
          echo "Build Date: $(date)" >> package/version.txt
          echo "Commit: ${{ github.sha }}" >> package/version.txt
          echo "Branch: ${{ github.ref_name }}" >> package/version.txt
          tar -czf SampleDotNetApp-${{ steps.version.outputs.version }}.tar.gz -C package .
          
      - name: Create Web API Package
        if: github.event.inputs.application_type == 'web-api' || github.event.inputs.application_type == 'both'
        run: |
          cd dotnet-webapi
          mkdir -p package
          cp -r publish/* package/
          echo "Version: ${{ steps.version.outputs.version }}" > package/version.txt
          echo "Build Date: $(date)" >> package/version.txt
          echo "Commit: ${{ github.sha }}" >> package/version.txt
          echo "Branch: ${{ github.ref_name }}" >> package/version.txt
          tar -czf SampleDotNetWebApi-${{ steps.version.outputs.version }}.tar.gz -C package .
          
      - name: Upload Console App Package
        if: github.event.inputs.application_type == 'console-app' || github.event.inputs.application_type == 'both'
        uses: actions/upload-artifact@v4
        with:
          name: console-app-package
          path: dotnet-app/SampleDotNetApp-${{ steps.version.outputs.version }}.tar.gz
          
      - name: Upload Web API Package
        if: github.event.inputs.application_type == 'web-api' || github.event.inputs.application_type == 'both'
        uses: actions/upload-artifact@v4
        with:
          name: web-api-package
          path: dotnet-webapi/SampleDotNetWebApi-${{ steps.version.outputs.version }}.tar.gz
          
      - name: Push Console App to Octopus
        if: github.event.inputs.application_type == 'console-app' || github.event.inputs.application_type == 'both'
        run: |
          echo "Pushing Console App package to Octopus Deploy..."
          curl -X POST "https://poc.octopus.app/api/packages/raw" \
            -H "X-Octopus-ApiKey: ${{ secrets.OCTOPUS_API_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@dotnet-app/SampleDotNetApp-${{ steps.version.outputs.version }}.tar.gz" \
            -F "overwriteMode=OverwriteExisting"
          echo "Console App package pushed successfully!"
            
      - name: Push Web API to Octopus
        if: github.event.inputs.application_type == 'web-api' || github.event.inputs.application_type == 'both'
        run: |
          echo "Pushing Web API package to Octopus Deploy..."
          curl -X POST "https://poc.octopus.app/api/packages/raw" \
            -H "X-Octopus-ApiKey: ${{ secrets.OCTOPUS_API_KEY }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@dotnet-webapi/SampleDotNetWebApi-${{ steps.version.outputs.version }}.tar.gz" \
            -F "overwriteMode=OverwriteExisting"
          echo "Web API package pushed successfully!"
            
      - name: Build Summary
        run: |
          echo "=== Build Summary ==="
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Build Number: ${{ github.run_number }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo ""
          echo "Applications Built:"
          if [ "${{ github.event.inputs.application_type }}" = "console-app" ] || [ "${{ github.event.inputs.application_type }}" = "both" ]; then
            echo "- Console Application: SampleDotNetApp-${{ steps.version.outputs.version }}.tar.gz"
          fi
          if [ "${{ github.event.inputs.application_type }}" = "web-api" ] || [ "${{ github.event.inputs.application_type }}" = "both" ]; then
            echo "- Web API Application: SampleDotNetWebApi-${{ steps.version.outputs.version }}.tar.gz"
          fi
          echo ""
          echo "Packages pushed to Octopus Deploy successfully!"
          echo "You can now create releases and deploy from the Octopus Deploy web interface." 