name: Destroy EC2 Instance

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Instance Name to Destroy'
        required: true
        type: string
        default: 'github-actions-ec2'
      
      aws_region:
        description: 'AWS Region'
        required: true
        type: choice
        options:
          - us-east-1
          - us-west-2
          - eu-west-1
          - ap-southeast-1
        default: 'us-east-1'

jobs:
  destroy-ec2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}
          
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        
      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="aws_region=${{ github.event.inputs.aws_region }}" \
            -var="key_name=${{ secrets.AWS_KEY_NAME }}" \
            -var="subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -auto-approve
            
      - name: Destroy Complete
        run: |
          echo "=== EC2 Instance Destroyed Successfully ==="
          echo "Instance Name: ${{ github.event.inputs.instance_name }}"
          echo "Region: ${{ github.event.inputs.aws_region }}"
          echo "All associated resources have been cleaned up." 