name: Run System Commands

on:
  workflow_dispatch:

jobs:
  system-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run system commands
        shell: bash
        run: |
          chmod +x scripts/system-info.sh
          ./scripts/system-info.sh
          
      - name: Command execution complete
        run: echo "System commands executed successfully!" 